return {}
-- return {
--   {
--     "nvim-neorg/neorg",
--     build = ":Neorg sync-parsers",
--     dependencies = { "nvim-lua/plenary.nvim" },
--     lazy = false,
--     config = function()
--       require("neorg").setup {
--         load = {
--           ["core.defaults"] = {}, -- Loads default behaviour
--           ["core.concealer"] = { config = { icon_preset = "diamond" } },
--           ["core.integrations.nvim-cmp"] = {},
--           ["core.integrations.treesitter"] = {},
--           ["core.keybinds"] = {
--             config = {
--               default_keybinds = true,
--               neorg_leader = "<Leader>o",
--             },
--           },
--           ["core.completion"] = {
--             config = {
--               engine  = "nvim-cmp"
--             }
--           },
--           ["core.dirman"] = { -- Manages Neorg workspaces
--             config = {
--               default_workspace = "notes",
--               workspaces = {
--                 notes = "~/notes",
--               },
--             },
--           },
--         },
--       }
--     end,
--   },
-- }
